name: Update badges

on:
  workflow_dispatch

jobs:
  update-readme:
    permissions: write-all
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
